### ISSUE TITLE
Fix issues with nav overlapping content

### ISSUE THREAD

**Issue by Tykki** [Tykki/portfolio#2]

**Comment by sra1kumar-NULL** [comment]
hey @Tykki  Can I work on this issue ? if you provide any picture or more description for the issue will be really helpful 
I'm ready for a quick chat or a call

**Comment by Tykki** [comment]
@sra1kumar-NULL Im sorry, I am not open to having others work in this repo. Feel free to maybe find some issues in the SavKeep repo to try out. I will also be putting up more open to work on projects later this week.

**Comment by Tykki** [comment]
Fixed with commit #981277f
